### ISSUE TITLE
Virtual memory

### ISSUE THREAD

**Issue by scorpiontornado** [jasminwu/1521-notes#5]
You're missing a key piece of information - virtual memory isn't simply "storing each segment in a different location in physical memory." Virtual memory is where the OS maps between a program’s illusory “virtual address space”, which is always 0-indexed, contiguous, and of undefined size, to the physical address space, in which the program could be stored at an arbitrary location in RAM, potentially fragmented and stored non-contiguously. This also guarantees security, where a program can only read/write to/from memory assigned to it.

This article explains it really well: https://www.internalpointers.com/post/introduction-virtual-memory

(sorry about the number of issues - the notes are great, keep it up!)

**Comment by jasminwu** [comment]
thx

**Comment by jasminwu** [comment]
okay fixed
